"""Broad discovery: each sector is scanned; no fixed investment favorites."""
SECTORS = [('반도체', '반도체|메모리|패키징', 'semiconductor|DRAM|advanced packaging'),
 ('전력망', '전력망|변압기|배전', 'power grid|transformer|switchgear'),
 ('발전', '발전소|가스터빈|원전', 'power generation|gas turbine|nuclear power'),
 ('배터리·ESS', '배터리|ESS|에너지저장', 'battery|energy storage|ESS'),
 ('태양광', '태양광|인버터', 'solar photovoltaic|solar inverter'),
 ('풍력', '풍력|해상풍력', 'wind power|offshore wind'),
 ('통신망', '통신망|광섬유|광통신', 'telecom network|fiber optics|optical communication'),
 ('데이터센터', '데이터센터|서버', 'data center|server infrastructure'),
 ('냉각·공조', '액체냉각|냉동기|공조', 'liquid cooling|chiller|HVAC'),
 ('조선', '조선|선박|엔진', 'shipbuilding|shipyard|marine engine'),
 ('해운·항만', '해운|항만|물류', 'shipping|port infrastructure|freight logistics'),
 ('광물·광산', '광산|구리|희토류', 'mining|copper mine|rare earth'),
 ('철강·금속', '철강|알루미늄|특수강', 'steel|aluminum|specialty metals'),
 ('화학·소재', '석유화학|특수가스|소재', 'petrochemicals|industrial gas|specialty chemicals'),
 ('석유·가스', '천연가스|LNG|정유', 'natural gas|LNG|oil refining'),
 ('수처리·물', '수처리|담수화|용수', 'water treatment|desalination|industrial water'),
 ('폐기물·재활용', '폐기물|재활용', 'waste management|recycling'),
 ('산업기계', '공작기계|산업기계', 'machine tools|industrial machinery'),
 ('로봇·자동화', '로봇|자동화|센서', 'industrial robotics|automation|industrial sensors'),
 ('건설·인프라', '건설|시멘트|인프라', 'construction|cement|civil infrastructure'),
 ('자동차', '자동차|전기차|부품', 'automotive|electric vehicle|auto components'),
 ('철도·육상운송', '철도|트럭|운송', 'rail freight|truck transport'),
 ('항공·우주', '항공|우주|위성', 'aviation|aerospace|satellite manufacturing'),
 ('방산', '방산|드론|탄약', 'defense industry|military drone|ammunition'),
 ('농업·비료', '농업|비료|종자', 'agriculture|fertilizer|crop seed'),
 ('식품·사료', '식품|사료|곡물', 'food manufacturing|animal feed|grain processing'),
 ('의료·진단', '의료기기|진단|병원', 'medical device|diagnostics|hospital equipment'),
 ('제약·바이오', '제약|바이오|생산', 'pharmaceutical manufacturing|biotechnology|drug production'),
 ('보험·금융', '보험|은행|결제', 'insurance|bank lending|financial services'),
 ('보안', '사이버보안|인증|암호', 'cybersecurity|digital identity|encryption'),
 ('소프트웨어', '소프트웨어|기업업무', 'enterprise software|workflow automation'),
 ('교육·노동', '교육|인력|직업훈련', 'education|vocational training|workforce training'),
 ('소비·유통', '유통|소비재|전자상거래', 'retail|consumer goods|ecommerce'),
 ('여행·숙박', '여행|호텔|관광', 'travel industry|hospitality|tourism'),
 ('부동산', '부동산|창고|임대', 'commercial real estate|warehouse leasing'),
 ('미디어·콘텐츠', '미디어|콘텐츠|광고', 'media industry|content licensing|advertising market'),
 ('섬유·포장', '섬유|포장|유리', 'textile|packaging|container glass'),
 ('반도체장비·부품', '반도체장비|진공펌프|챔버', 'semiconductor equipment|vacuum pump|process chamber'),
 ('임업·목재', '임업|목재|목조건축', 'forestry|timber|mass timber'),
 ('펄프·제지', '펄프|제지|종이포장', 'pulp|paper manufacturing|paper packaging'),
 ('수산·양식', '수산|양식|수산사료', 'aquaculture|fisheries|aquafeed'),
 ('축산·동물의약', '축산|동물백신|동물의약', 'livestock|animal vaccine|animal health'),
 ('종묘·농기계', '종묘|농기계|관개', 'seed genetics|farm machinery|irrigation'),
 ('콜드체인', '콜드체인|냉장물류|냉동창고', 'cold chain|refrigerated logistics|cold storage'),
 ('고령자·돌봄', '요양|돌봄|실버산업', 'elder care|long term care|assisted living'),
 ('치과·안과·청각', '치과|안과|보청기', 'dental devices|ophthalmology|hearing aids'),
 ('의료위탁·임상', 'CDMO|임상시험|의약품위탁', 'CDMO|contract research|clinical trials'),
 ('미용·퍼스널케어', '화장품|미용기기|위생용품', 'cosmetics|beauty devices|personal care'),
 ('반려동물', '반려동물|펫푸드|동물병원', 'pet food|pet care|veterinary services'),
 ('주거개보수', '주택개보수|단열재|창호', 'home renovation|building insulation|replacement windows'),
 ('생활가전', '생활가전|주방가전|가정용로봇', 'home appliances|kitchen appliances|domestic robots'),
 ('스포츠·레저', '스포츠산업|레저|피트니스', 'sports equipment|leisure industry|fitness services'),
 ('장례·추모', '장례산업|화장시설|추모시설', 'funeral services|cremation|death care'),
 ('업무위탁·시설관리', '업무위탁|시설관리|산업세탁', 'business process outsourcing|facility management|industrial laundry'),
 ('인력중개', '인력파견|채용시장|외국인근로자', 'staffing industry|recruitment|labor migration'),
 ('렌탈·리스', '장비렌탈|산업리스|가전렌탈', 'equipment rental|industrial leasing|appliance rental'),
 ('시험·인증', '시험인증|비파괴검사|품질인증', 'testing inspection certification|nondestructive testing|product certification'),
 ('법률·회계', '법률서비스|회계서비스|세무자동화', 'legal services|accounting services|tax automation'),
 ('데이터·정보서비스', '데이터거래|신용정보|데이터라이선스', 'data licensing|credit bureau|information services'),
 ('공간정보·측량', '공간정보|측량|디지털트윈', 'geospatial|surveying|digital twin'),
 ('방송·영상장비', '방송장비|영상제작장비|전문오디오', 'broadcast equipment|video production equipment|professional audio'),
 ('결제·핀테크', '전자결제|송금|핀테크', 'payment processing|remittance|fintech infrastructure'),
 ('재보험·기후보험', '재보험|기후보험|보험료율', 'reinsurance|climate insurance|insurance pricing'),
 ('거래소·시장인프라', '거래소|청산결제|수탁', 'exchange operator|clearing house|securities custody'),
 ('양자컴퓨팅', '양자컴퓨팅|극저온장비|양자센서', 'quantum computing|cryogenic equipment|quantum sensing'),
 ('수소·암모니아', '수소|암모니아|수전해', 'hydrogen production|ammonia|electrolyzer'),
 ('지열', '지열|심부지열|지열시추', 'geothermal|enhanced geothermal|geothermal drilling'),
 ('바이오연료', '바이오연료|지속가능항공유|바이오가스', 'biofuel|sustainable aviation fuel|biogas'),
 ('탄소포집·배출권', '탄소포집|탄소저장|배출권', 'carbon capture|carbon storage|emissions trading'),
 ('대기·환경측정', '대기오염방지|환경측정|집진', 'air pollution control|environmental monitoring|industrial filtration'),
 ('핵연료·폐로', '핵연료|우라늄농축|원전폐로', 'nuclear fuel|uranium enrichment|nuclear decommissioning'),
 ('해저케이블', '해저케이블|케이블포설|해저통신', 'subsea cable|cable laying|submarine communication'),
 ('위치·항법', '위성항법|관성항법|위치측정', 'satellite navigation|inertial navigation|positioning systems'),
 ('전자수동부품', 'MLCC|커패시터|인덕터', 'MLCC|capacitor|inductor'),
 ('기판·커넥터', 'PCB|커넥터|기판', 'printed circuit board|electrical connector|IC substrate'),
 ('모터·감속기·베어링', '모터|감속기|베어링', 'electric motor|precision gearbox|industrial bearing'),
 ('펌프·밸브·유압', '펌프|밸브|유압', 'industrial pump|industrial valve|hydraulics'),
 ('계측·검사', '계측|정밀측정|머신비전', 'metrology|test equipment|machine vision'),
 ('접착·코팅·복합재', '접착제|코팅|복합재', 'industrial adhesive|protective coating|composite materials'),
 ('유리·세라믹·내화물', '특수유리|세라믹|내화물', 'specialty glass|technical ceramics|refractory materials')]
# Driver scans catch links that do not yet have an established sector label.
DRIVERS = [
 ('용도 변화', '"new application" OR "new end market" OR "demand shift"'),
 ('공급 경직', '"lead times" OR "capacity shortage" OR "plant closure"'),
 ('고객 행동', '"prepayment" OR "long-term supply agreement" OR "take-or-pay"'),
 ('원가·대체', '"cost parity" OR "commercial deployment" OR "substitution"'),
 ('정책 집행', '"contract awarded" OR "funding disbursed" OR "export restriction"'),
 ('인구·생활방식', '"aging population" OR "household formation" OR "consumer behavior shift"'),
 ('기후·적응', '"climate adaptation" OR "water scarcity" OR "heat resilience"'),
 ('인력·생산성', '"labor shortage" OR "process automation" OR "outsourcing demand"'),
 ('규격·의무화', '"mandatory standard" OR "compliance deadline" OR "building code change"'),
 ('무역·현지화', '"local content requirement" OR "supply chain relocation" OR "reshoring"'),
 ('안보·복원력', '"strategic stockpile" OR "supply diversification" OR "critical infrastructure"'),
 ('증설·반증', '"capacity expansion" OR "order cancellation" OR "oversupply"'),
]
# Official-domain hints; primary evidence still needs agreement in analysis and audit.
# Unlisted industries and issuers are assessed on the same source-origin criteria.
DEFAULT_PRIMARY_DOMAINS = [
 'energy.gov', 'eia.gov', 'iea.org', 'irena.org', 'sec.gov', 'europa.eu',
 'motie.go.kr', 'kostat.go.kr', 'data.go.kr', 'nvidia.com', 'samsung.com',
 'skhynix.com', 'micron.com', 'tsmc.com', 'gevernova.com', 'siemens-energy.com',
 'catl.com', 'ir.tesla.com', 'firstsolar.com', 'vestas.com', 'ericsson.com',
 'nokia.com', 'cisco.com', 'corning.com', 'hhi.co.kr', 'hd.com',
]
